#
# This Docker Compose file will create a complete system to run this demo.
#

version: '2.1'

services:

  pravega:
    image: pravega/pravega:0.3.0-SNAPSHOT
    ports:
      - "9090:9090"
      - "12345:12345"
    command: standalone
    environment:
      HOST_IP: ${PRAVEGA_HOST_ADDRESS:-pravega}

  gateway:
    image: claudiofahey/nautilus_iiot_demo_gateway
    build:
      context: gateway
    ports:
      - "3000:3000"
    environment:
      PRAVEGA_CONTROLLER: tcp://${PRAVEGA_HOST_ADDRESS:-pravega}:${PRAVEGA_PORT:-9090}
      PRAVEGA_MIN_NUM_SEGMENTS: "2"
      PRAVEGA_SCOPE: "iot"
      PRAVEGA_TARGET_RATE_EVENTS_PER_SEC: "50"
      ROUTING_KEY_ATTRIBUTE_NAME: "device_id"
    restart: on-failure

  streaming_data_generator:
    image: claudiofahey/nautilus_iiot_demo_streaming_data_generator
    build:
      context: streaming_data_generator
    command:
      - ./streaming_data_generator.py
      - --gateway-url
      - http://gateway:3000/data
      - --num-devices
      - "2"
