---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-processor-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-driver-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      #- delete    # Delete permission removed so the logs remain available to inspect after termination.
      - get
      - watch
      - list
      - create
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: spark-processor-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-driver-role
subjects:
  - kind: ServiceAccount
    name: spark-processor-service-account
