/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pravega.example.iiotdemo.flinkprocessor;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TempData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3073210133565580541L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TempData\",\"namespace\":\"io.pravega.example.iiotdemo.flinkprocessor\",\"fields\":[{\"name\":\"temp_celsius\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TempData> ENCODER =
      new BinaryMessageEncoder<TempData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TempData> DECODER =
      new BinaryMessageDecoder<TempData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TempData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TempData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TempData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TempData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TempData from a ByteBuffer. */
  public static TempData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double temp_celsius;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TempData() {}

  /**
   * All-args constructor.
   * @param temp_celsius The new value for temp_celsius
   */
  public TempData(java.lang.Double temp_celsius) {
    this.temp_celsius = temp_celsius;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return temp_celsius;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: temp_celsius = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'temp_celsius' field.
   * @return The value of the 'temp_celsius' field.
   */
  public java.lang.Double getTempCelsius() {
    return temp_celsius;
  }

  /**
   * Sets the value of the 'temp_celsius' field.
   * @param value the value to set.
   */
  public void setTempCelsius(java.lang.Double value) {
    this.temp_celsius = value;
  }

  /**
   * Creates a new TempData RecordBuilder.
   * @return A new TempData RecordBuilder
   */
  public static io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder newBuilder() {
    return new io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder();
  }

  /**
   * Creates a new TempData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TempData RecordBuilder
   */
  public static io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder newBuilder(io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder other) {
    return new io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder(other);
  }

  /**
   * Creates a new TempData RecordBuilder by copying an existing TempData instance.
   * @param other The existing instance to copy.
   * @return A new TempData RecordBuilder
   */
  public static io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder newBuilder(io.pravega.example.iiotdemo.flinkprocessor.TempData other) {
    return new io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder(other);
  }

  /**
   * RecordBuilder for TempData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TempData>
    implements org.apache.avro.data.RecordBuilder<TempData> {

    private double temp_celsius;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.temp_celsius)) {
        this.temp_celsius = data().deepCopy(fields()[0].schema(), other.temp_celsius);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TempData instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pravega.example.iiotdemo.flinkprocessor.TempData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.temp_celsius)) {
        this.temp_celsius = data().deepCopy(fields()[0].schema(), other.temp_celsius);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'temp_celsius' field.
      * @return The value.
      */
    public java.lang.Double getTempCelsius() {
      return temp_celsius;
    }

    /**
      * Sets the value of the 'temp_celsius' field.
      * @param value The value of 'temp_celsius'.
      * @return This builder.
      */
    public io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder setTempCelsius(double value) {
      validate(fields()[0], value);
      this.temp_celsius = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'temp_celsius' field has been set.
      * @return True if the 'temp_celsius' field has been set, false otherwise.
      */
    public boolean hasTempCelsius() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'temp_celsius' field.
      * @return This builder.
      */
    public io.pravega.example.iiotdemo.flinkprocessor.TempData.Builder clearTempCelsius() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TempData build() {
      try {
        TempData record = new TempData();
        record.temp_celsius = fieldSetFlags()[0] ? this.temp_celsius : (java.lang.Double) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TempData>
    WRITER$ = (org.apache.avro.io.DatumWriter<TempData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TempData>
    READER$ = (org.apache.avro.io.DatumReader<TempData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
