apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-data-generator
  labels:
    app: nautilus-iiot-demo
    component: video-data-generator
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: nautilus-iiot-demo
      component: video-data-generator
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: nautilus-iiot-demo
        component: video-data-generator
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ .Release.Namespace }}-pravega
      containers:
        - name: main
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          command: ["video_data_generator.py"]
          env:
            - name: GENERATOR_AVG_DATA_SIZE
              value: "{{ .Values.video_generator.avg_data_size }}"
            - name: GENERATOR_FPS
              value: "{{ .Values.video_generator.fps }}"
            - name: GENERATOR_GATEWAY
              value: "{{ .Values.generator.gateway }}"
            - name: GENERATOR_STREAM
              value: "{{ .Values.video_generator.stream }}"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "2000m"
