apiVersion: v1
kind: Pod
metadata:
  name: video-data-generator
  labels:
    app: nautilus-iiot-demo
    component: video-data-generator
    release: {{ .Release.Name }}
spec:
  serviceAccount: {{ .Release.Namespace }}-pravega
  containers:
  - name: main
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: Always
    command: ["video_data_generator.py"]
    env:
      - name: GENERATOR_GATEWAY
        value: "{{ .Values.generator.gateway }}"
      - name: GENERATOR_FPS
        value: "{{ .Values.video_generator.fps }}"
