hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

prePuller:
  hook:
    enabled: false

singleuser:
  defaultUrl: "/lab"
  extraEnv:
    pravega_client_auth_method: "Bearer"
    pravega_client_auth_loadDynamic: "true"
    KEYCLOAK_SERVICE_ACCOUNT_FILE: "/var/run/secrets/nautilus.dellemc.com/serviceaccount/keycloak.json"
  image:
    name: jupyter/minimal-notebook
    tag: ae5f7e104dd5
  imagePullPolicy: Always
  profileList:

#    - display_name: "Spark 2.4.0"
#      default: true
#      description: "Currently working with Pravega"
#      kubespawner_override:
#        image: hop-claudio-minikube-1.solarch.lab.emc.com:31001/all-spark-notebook:2343e33dec46

    - display_name: "Spark 2.4.1"
      default: true
      description: "Apache Spark with Pravega Connectors"
      kubespawner_override:
        image: hop-claudio-minikube-1.solarch.lab.emc.com:31001/all-spark-notebook:f646d2b2a3af

#    - display_name: "Spark 2.4.2"
#      description: "Not working yet"
#      kubespawner_override:
#        image: hop-claudio-minikube-1.solarch.lab.emc.com:31001/all-spark-notebook:ae5f7e104dd5

    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."

    - display_name: "Data Science environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:ae5f7e104dd5

  storage:
    extraVolumes:
      - name: examples-pravega
        secret:
          secretName: examples-pravega
      - name: data-project
        persistentVolumeClaim:
          claimName: data-project
    extraVolumeMounts:
      - name: examples-pravega
        mountPath: /var/run/secrets/nautilus.dellemc.com/serviceaccount
      - name: data-project
        mountPath: /home/jovyan/data-project
