hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

prePuller:
  hook:
    enabled: false

singleuser:
  defaultUrl: "/lab"
  extraEnv:
    pravega_client_auth_method: "Bearer"
    pravega_client_auth_loadDynamic: "true"
    KEYCLOAK_SERVICE_ACCOUNT_FILE: "/var/run/secrets/nautilus.dellemc.com/serviceaccount/keycloak.json"
  image:
    name: jupyter/minimal-notebook
    tag: ae5f7e104dd5
  profileList:

    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true

    - display_name: "Data Science environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:ae5f7e104dd5

    - display_name: "Spark 2.4.0"
      description: "Currently working with Pravega"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46

    - display_name: "Spark 2.4.2"
      description: "Not working yet"
      kubespawner_override:
        image: jupyter/all-spark-notebook:ae5f7e104dd5

  storage:
    extraVolumes:
      - name: examples-pravega
        secret:
          secretName: examples-pravega
    extraVolumeMounts:
      - name: examples-pravega
        mountPath: /var/run/secrets/nautilus.dellemc.com/serviceaccount
